### ISSUE TITLE
Configure default cache

### ISSUE THREAD

**Issue by jimmidyson** [infinispan/infinispan-spring-boot#10]
Any hints how to configure the default cache programatically?

**Comment by slaskawi** [comment]
Infinispan auto-configuration kicks in only [if there's no `EmbeddedCacheManager`](https://github.com/infinispan/infinispan-spring-boot/blob/master/inifinispan-spring-boot-starter-autoconfigure/src/main/java/infinispan/autoconfigure/embedded/InfinispanEmbeddedAutoConfiguration.java#L24). You might create it yourself and supply the default configuration into the constructor:

```
@Bean
public EmbeddedCacheManager defaultCacheManager() {
    Configuration c = ...;
    return new DefaultCacheManager(c);
}
```

**Comment by jimmidyson** [comment]
Aha! Perfect thanks!
