### ISSUE TITLE
How can "invalid mode can be used with shared cache storage." ？

### ISSUE THREAD

**Issue by a544793138** [infinispan/infinispan-spring-boot#105]
Hello, I have a springboot project used infinispan to run the invalidation mode under the cluster for cache.

In fact, I saw `"In invalidation, the caches on different nodes do not actually share any data"` and now I am in this situation. Although I use the method you provided: `Cache.putForExternalRead(key, value)` and method can solve the problem that when I puts the data into the cache of the Node A, the B node invalidates it, I can't use the springboot annotations, such as @CacheableThis.

However I also saw `"Invalidation mode can be used with a shared cache store."`. I don't know how to do this and I hope you can provide some help.

The goal I hope to achieve is that in the invalidation mode, I put the data into the cache of the Node A without causing the invalidation of the Node B. Only when I update or delete the data on the A node, the data corresponding to the Node B is invalid.

Looking forward to your help. Thanks

**Comment by karesti** [comment]
Hi, we don't use issues for infinispan questions. Would you please use zulip  or stackoverflow for questions, please? https://infinispan.zulipchat.com
Meanwhile, I will grab a look to invalidation mode + spring support in infinispan. thanks!
