### ISSUE TITLE
InfinispanEmbeddedAutoConfiguration starts DefaultCacheManager too early

### ISSUE THREAD

**Issue by dominioon** [infinispan/infinispan-spring-boot#130]
It is not possible to declare cluster listeners before DefaultCacheManager starts. The following code does not work (ie, does not print "Cache started"):

##### ClusterListener.java
```Java
@Listener
public class ClusterListener {
  @CacheStarted
  public void cacheStarted(CacheStartedEvent event) {
    System.out.println("Cache started");
  }
}
```

##### CacheConfiguration.java
```Java
@Configuration
@EnableCaching
public class CacheConfiguration {
  @Bean
  InfinispanGlobalConfigurationCustomizer globalConfigurationCustomizer() {
    return builder -> builder.transport().defaultTransport();
  }

  @Bean
  InfinispanCacheConfigurer cacheConfigurer() {
    return manager -> manager.addListener(new ClusterListener());
  }
}
```

The reason is that [new DefaultCacheManager(GlobalConfiguration,Configuration)](https://github.com/infinispan/infinispan-spring-boot/blob/115d6a6b7dfab0b523610d107985feaf8f69a0e9/infinispan-spring-boot-starter-embedded/src/main/java/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfiguration.java#L80) internally starts DefaultCacheManager (which in order triggers CacheStartedEvent) before [cache configurers are executed](https://github.com/infinispan/infinispan-spring-boot/blob/115d6a6b7dfab0b523610d107985feaf8f69a0e9/infinispan-spring-boot-starter-embedded/src/main/java/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfiguration.java#L84). Maybe it should be like:
```Java
         ...
         manager = new DefaultCacheManager(configXml, false);
         ...
         manager = new DefaultCacheManager(globalConfigurationBuilder.build(), configurationBuilder.build(), false);
      }

      cacheConfigurations.forEach(manager::defineConfiguration);
      configurers.forEach(configurer -> configurer.configureCache(manager));

      manager.start();

      return manager;
    }
```

**Comment by karesti** [comment]
@dominioon  nice catch, correction coming in the next release

**Comment by karesti** [comment]
https://issues.redhat.com/browse/ISPN-11195
