### ISSUE TITLE
Update Spring documentation

### ISSUE THREAD

**Issue by slaskawi** [infinispan/infinispan-spring-boot#17]
There are at least 2 spots which need to be updated:
* http://docs.spring.io/spring-boot/docs/1.4.1.RELEASE/reference/htmlsingle/#boot-features-caching-provider-infinispan
* https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-cache

**Comment by slaskawi** [comment]
The [Spring Caching](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-samples/spring-boot-sample-cache/pom.xml#L119-L131) documentation doesn't need updating. If we wanted to use Spring Boot Starters there, we would need to introduce 3 dependencies:
* Infinispan Spring Boot Starter
* JCache (since the demo is based on JCache...)
* And Infinispan Spring Embedded artifact. 

So we would make things worse actually. However I think it is worth to mention that we have Spring Boot Starters.

**Comment by slaskawi** [comment]
Submitted both pull requests. Let's wait for some update...

**Comment by slaskawi** [comment]
PR: https://github.com/spring-projects/spring-boot/pull/8592

**Comment by karesti** [comment]
The PR has been closed on spring side
