### ISSUE TITLE
Move code to proper packages

### ISSUE THREAD

**Issue by slaskawi** [infinispan/infinispan-spring-boot#19]

**Comment by lburgazzoli** [comment]
I have some spare time to work on this, what would be the proper packages ?

**Comment by slaskawi** [comment]
I thought about moving stuff to `org.infinispan.spring.starter.*`. But honestly now I'm having second thoughts whether this is still important since remote and embedded starters are in separate jars. 

Let me think about it a little but more but for now I lean towards to closing this issue without any changes.
