### ISSUE TITLE
Support spring.config.type property

### ISSUE THREAD

**Issue by slaskawi** [infinispan/infinispan-spring-boot#23]
[The Spring Team suggested](https://github.com/spring-projects/spring-boot/pull/8592#issuecomment-288075297) that we could detect `spring.config.type` and detect Infinispan Caching support automatically. This way we could remove the code duplication between our teams.

**Comment by lburgazzoli** [comment]
I've create an experimental [branch](https://github.com/lburgazzoli/infinispan-spring-boot/commit/b6279cf457540cc0984600e9d3136df02096f6a7) for this issue in which there is an additional check that does:

```java
String cacheType = context.getEnvironment().getProperty("spring.cache.type");
return cacheType == null || CacheType.INFINISPAN.name().equalsIgnoreCase(cacheType);
```
Assumptions:
- the name of the property should be ``spring.cache.type`` not ``spring.config.type``
- if one sets ``spring.cache.type = INFINISPAN`` ifinispan's own starters take the precedence as now the auto configurer are annotated with ``@AutoConfigureBefore(CacheAutoConfiguration.class)``

There is still an open point as spring boot does not auto configure its own infinispan cache manager if a bean of type ``EmbeddedCacheManager`` is already there but it does not check for ``RemoteCacheManager``.

**Comment by slaskawi** [comment]
That's really interesting @lburgazzoli! 

I believe you implemented the correct approach (when both starters are on classpath, our kicks in). May I ask you to issue a PR? After we merge it, we could do some testing with different examples and if everything is ok, do the `2.0.0.Alpha1` release.

So the original Spring Boot starters seem to favor embedded use case over remote. I think that would be OK for now (we can ask them to change the behavior later or even issue a PR). I don't foresee any major consequences because of this... WDYT?

**Comment by lburgazzoli** [comment]
I will open a PR soon and yeah, I do not see any major issue because of the embedded cache created by spring boot, the only thing is that you may end up having both a remote and an embedded cache manager that may be not what you want.

**Comment by slaskawi** [comment]
The cool thing is that with our extension you can disable both separately. Also created (but not started) DefaultCacheManager doesn't consume that much of the resources. It think it should be a bit deal.

**Comment by lburgazzoli** [comment]
PR opened
