### ISSUE TITLE
add infinispan-spring-boot-starter-remote to maven

### ISSUE THREAD

**Issue by Tempys** [infinispan/infinispan-spring-boot#36]
Please add this dependency to maven

**Comment by slaskawi** [comment]
Please note, that version currently checked into `master` branch is in development phase. The `infinispan-spring-boot-starter-remote` artifact will be present in `2.0.0.Alpha1`, which should happen fairly soon. Stay tuned...

**Comment by slaskawi** [comment]
All the bits have been released. Please note that JBoss Nexus sync takes a while. See https://github.com/infinispan/infinispan-spring-boot/releases/tag/2.0.0.Beta1
