### ISSUE TITLE
Spring boot Examples

### ISSUE THREAD

**Issue by fxviking** [infinispan/infinispan-spring-boot#4]
hi, 

As per the readme, a link to examples is given https://github.com/blocha/infinispan-simple-tutorials , and mentioned to look for spring boot .

But i don't see any spring boot examples there, is it not updated on the repository ?

**Comment by slaskawi** [comment]
Hey @fxviking,

I plan to release the quickstarts this week and update all the links.

In the meantime, the Spring Boot tutorial is in review: https://github.com/infinispan/infinispan-simple-tutorials/pull/19

Thanks,
Sebastian

**Comment by fxviking** [comment]
Ok great
