### ISSUE TITLE
Spring Cache issue

### ISSUE THREAD

**Issue by geoand** [infinispan/infinispan-spring-boot#40]
Hi,

I am investigating how Infinispan can be used with Spring Boot and following the instructions in the README, I noticed the following:

Although the README mentions that `infinispan-spring4-remote` or `infinispan-spring4-embedded` are needed only when integration with Spring-Session is desired and no mention of these artifacts is made when a simple integration with Spring Cache is needed, I was however not able to get Spring Cache working without them.
Am I missing something obvious here or is the README slightly our of date? In such a case I can create a PR to fix it.

Thanks

**Comment by slaskawi** [comment]
Both artifacts (the Spring integration [embedded](https://github.com/infinispan/infinispan-spring-boot/blob/master/infinispan-spring-boot-starter-embedded/pom.xml#L27-L29) and [remote](https://github.com/infinispan/infinispan-spring-boot/blob/master/infinispan-spring-boot-starter-remote/pom.xml#L26-L29)) should be pulled transitively by Maven. Could you please tell me more how do you build your project?

**Comment by geoand** [comment]
I just included the following dependencies

```
                <dependency>
                    <groupId>org.infinispan</groupId>
                    <artifactId>infinispan-spring-boot-starter</artifactId>
                    <version>${version.infinispan.starter}</version>
                </dependency>
                <dependency>
                    <groupId>org.infinispan</groupId>
                    <artifactId>infinispan-core</artifactId>
                    <version>${version.infinispan}</version>
                </dependency>
```

using 

```
    <properties>
        <version.infinispan.starter>1.0.0.Final</version.infinispan.starter>
        <version.infinispan>9.0.0.Final</version.infinispan>
    </properties>
```

I am using [this](https://github.com/snowdrop/spring-boot-booster-parent) following Maven parent.
I will also try the configuration using the default Spring Boot parent and report back

**Comment by slaskawi** [comment]
Right... I know what happened...

A while ago we decided to split this started into two - remote and embedded. Starting from that point you only need to specify only one dependency - `infinispan-spring-boot-starter-embedded` or `infinispan-spring-boot-starter-remote`. 

The code moved forward but it seems we didn't update the docs nor the [tutorial](https://github.com/infinispan/infinispan-simple-tutorials/blob/master/spring-boot/pom.xml#L35).

Of course, if you have a minute, we would love to get a PR adding those changes to the READ.ME. However, if you are busy - no worries, I will introduce those changes shortly.

**Comment by geoand** [comment]
I see! Thanks for the info!
I will try it out and once I get it working, I will create a PR with the new instructions.

**Comment by geoand** [comment]
I just opened PR #41 :)
