### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by erikkemperman** [infinispan/infinispan-spring-boot#44]
It seems 2.0.0.Alpha1 is from a while ago, in the meantime there were significant bumps to spring-boot as well as infinispan parts. Any chance of a new release of the starters?

Thanks in advance!

**Comment by slaskawi** [comment]
Thanks for the reminder! https://github.com/infinispan/infinispan-spring-boot/releases/tag/2.0.0.Beta1

**Comment by erikkemperman** [comment]
Thanks!!

**Comment by erikkemperman** [comment]
@slaskawi Ah, sorry, I had expected the dependencies would be upgraded? 

https://github.com/infinispan/infinispan-spring-boot/blob/master/pom.xml#L41-L43

I would like to use this with spring-boot 2 and infinispan 9 :-)

**Comment by slaskawi** [comment]
That's a good point. However you can always to this manually by specifying both BOMs in your `dependencyManagement` section:

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.infinispan</groupId>
                <artifactId>infinispan-bom</artifactId>
                <version>${infinispan.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
    </dependencyManagement>
```

**Comment by erikkemperman** [comment]
Thanks, at the moment our POM is a child of spring-boot-dependencies (indirectly, via spring-platform), so that should be pretty close to what you suggest -- but we are using infinispan artifacts directly, not through its BOM. I'll try that when I find some time.

My previous attempt failed on some bean creation, and my first thought (but didn't track it down completely because I was in a hurry) was that it might be due to infinispan's `spring4-embedded` artifact (with spring-boot 2 we get spring 5).
