### ISSUE TITLE
Provide automatic translation of Hot Rod client properties into Spring YAML

### ISSUE THREAD

**Issue by slaskawi** [infinispan/infinispan-spring-boot#48]
Currently we manually translate some of the Hot Rod client properties into Spring YAML. This will be a pretty big maintenance burden in the future. We need to figure out a way to translate *all* of the properties into Spring format.

**Comment by juliojgd** [comment]
Hi, I agree. In my current project, client has requested to be able to set any hotrod client property through Spring Yaml with no need to write the hotrod.properties file.
What we've done is:
1.-Load from Spring yaml into a ConfigurationProperties object below our custom property namespace:
client-root:
  common:
     cache:
        hotrod-client:
            [all-hotrod-client-properties-here-even-pool-ones]
2.-Create a Properties object from the object loaded in 1.
3.-Define a @Bean (InfinispanRemoteConfigurer) inside our Autoconfiguration class that uses ConfigurationBuilder.withProperties method.

We have been capable of doing this with 2.0.0.Beta1 or 2.0.0.CR1-SNAPSHOT as these versions have fixed the @Condition issue that forced a "too early" creation of the Bean.

Is this an acceptable way to do this?
Thanks

**Comment by slaskawi** [comment]
Yes, that sounds really good. 

The only thing that needs a thought is the prefix for Hot Rod client properties. Currently we use [this](https://github.com/infinispan/infinispan-spring-boot/blob/master/infinispan-spring-boot-starter-remote/src/test/resources/test-application.properties):

```
infinispan.remote.server-list=127.0.0.1:6667
infinispan.remote.socket-timeout=10
infinispan.remote.connect-timeout=10
infinispan.remote.max-retries=10
```

Since it nicely separates embedded and remove, I think we should preserve them. 

@juliojgd Do you have an example, or maybe would you like to contribute a PR?

**Comment by juliojgd** [comment]
@slaskawi Sure, let me polish the code and I'll contribute the PR.
I was thinking about this:
Prefix `infinispan.remote.hotrod-client` prefix as they are not only "remote" properties but also related specifically with the Hotrod client and its connection pool.
So, sample:

```
# Sample Hotrod client connection pool related properties 
infinispan.remote.hotrod-client.minIdle
infinispan.remote.hotrod-client.maxActive
infinispan.remote.hotrod-client.minEvictableIdleTimeMillis

# Sample Hotrod client properties (not directly related to connection pool)
infinispan.remote.hotrod-client.infinispan.client.hotrod.max_retries
infinispan.remote.hotrod-client.infinispan.client.hotrod.socket_timeout
```
I know the names of the second group are somehow redundant but this is the most straightforward way I found to configure it the way I told.

The names of the properties will be exactly those found in a valid `hotrod.properties` file, as the intnention of that properties is to be injected as a Properties object to a ConfigurationBuilder object, not to be used in Spring.

Perhaps we can make aliases for:

```
infinispan.remote.hotrod-client.infinispan.client.hotrod.server_list=${infinispan.remote.server-list}
infinispan.remote.hotrod-client.infinispan.client.hotrod.socket_timeout=${infinispan.remote.socket-timeout}
infinispan.remote.hotrod-client.infinispan.client.hotrod.connect_timeout=${infinispan.remote.connect-timeout}
infinispan.remote.hotrod-client.infinispan.client.hotrod.max_retries=${infinispan.remote.max-retries}
```

If you prefer to remove the `infinispan.client.hotrod` in the middle of the property key (e.g. `infinispan.remote.hotrod-client.max_retries` and `infinispan.remote.hotrod-client.pool.maxActive` (for pool ones)) please tell me and I'll figure out how to rearrange.

Regards

**Comment by rgordill** [comment]
In my opinion, naming convention should be simple and consistent with other spring cache alternatives. According with https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html#boot-features-caching-provider-infinispan, they propose the prefix:

spring.cache.infinispan

So I will keep that, using embedded or remote depending on the use case. To uniform more with springboot, I suggest to substitute the "_" with "-" , so, I will go for example:

Original client hotrod properties:
```
infinispan.client.hotrod.server_list
infinispan.client.hotrod.use_ssl
```
Spring boot ones:
```
spring.cache.infinispan.remote.server-list
spring.cache.infinispan.remote.use-ssl
```

@juliojgd , I don't get the difference between the two groups you mention. socket-timeout, connect-timeout, etc, IMHO refers also to connection details.

**Comment by slaskawi** [comment]
Ok, let me navigate back a little bit and clear some things out. At first we have a set of properties from `hotrod-client.properties` file. They look like that:

```
infinispan.client.hotrod.server_list = 127.0.0.1:11222
```

You can fine the full list [here](https://github.com/infinispan/infinispan/blob/master/client/hotrod-client/src/test/resources/hotrod-client.properties).

The next thing are Spring Boot `application.yaml` properties. They look at the moment like that:

```
infinispan.remote.server-list=127.0.0.1:6667
```

A few things to notice here:

1. We do not use `client.hotrod` string in the `application.yaml` since they were quite redundant. `hotrod` is the only protocol supported by this starter (but this might change in mid to long term future because of the [Single Port feature](https://github.com/infinispan/infinispan/pull/5728)) and `client` is quite obvious since we are using the `remote` starter. 
2. We use `-` instead of `_`. This is Spring convention.
3. When we were implementing this starters, Spring folks asked us not to use `spring` in the properties names since they indicate built-in support for certain integrations. I'll be talking more on that a bit lower in this message.

So now, with all this in mind, let me answer some comments.

> Prefix infinispan.remote.hotrod-client prefix as they are not only "remote" properties but also related specifically with the Hotrod client and its connection pool.

Yes, this is true for today. It may change in the future with multi-protocol clients though. However, that's distant future. I believe, it's a safe bet to assume that this starters will support only the Hot Rod protocol. With this in mind, the `hotrod` name can be omitted. I would advocate for keeping it as is (using `infinispan.remote.server-list` as an example). Changing that would require us to implement aliases or otherwise we would break client applications. Therefore I guess we have no good reason for changing this convention (but again, we can do it any major release).

> If you prefer to remove the infinispan.client.hotrod in the middle of the property key (e.g. infinispan.remote.hotrod-client.max_retries and infinispan.remote.hotrod-client.pool.maxActive (for pool ones)) please tell me and I'll figure out how to rearrange.

Yes, I think we should do this translation step and use properties like this:

```
infinispan.remote.max_retries
infinispan.remote.connect_timeout
```

> In my opinion, naming convention should be simple and consistent with other spring cache alternatives. According with https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html#boot-features-caching-provider-infinispan, they propose the prefix: spring.cache.infinispan

Spring has some basic Infinispan support built-in. The manual entry you sent, refers to it. However, this project contains alternative starter with many more features. I recommend using it *instead* of Infinispan support built into Spring.

**Comment by tristantarrant** [comment]
I wouldn't go out of my way to conjure up new names for properties just for the sake of changing them.

**Comment by vadimkim** [comment]
Hi, what is the status of this task right now? Should I use approach of @juliojgd  or it can be done in a better way?

**Comment by tristantarrant** [comment]
In order to reduce the amount of boilerplate code and centralize this kind of thing I think we should enhance the https://github.com/infinispan/infinispan/blob/master/client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java class with setters for all properties. At this point, https://github.com/infinispan/infinispan-spring-boot/blob/master/infinispan-spring-boot-starter-remote/src/main/java/org/infinispan/spring/starter/remote/InfinispanRemoteConfigurationProperties.java can just *extend* it while adding the @ConfigurationProperties annotation

**Comment by rgordill** [comment]
There is a risk of misalignment between properties and the springboot configuration properties. I think it would be less risky if we can add an annotation on the ConfigurationProperties.java, that automatically adds the springboot configuration.

WDYT?

**Comment by tristantarrant** [comment]
That is exactly what I propose, but I'd keep the Spring annotation on InfinispanRemoteConfigurationProperties:
`@ConfigurationProperties
public class InfinispanRemoteConfigurationProperties extends org.infinispan.client.hotrod.impl.ConfigurationProperties {}`

**Comment by rgordill** [comment]
+1

**Comment by tristantarrant** [comment]
https://issues.jboss.org/browse/ISPN-9398

**Comment by karesti** [comment]
https://issues.jboss.org/browse/ISPN-9437
