### ISSUE TITLE
More information (example) for @EnableInfinispanEmbeddedHttpSession is needed

### ISSUE THREAD

**Issue by vadimkim** [infinispan/infinispan-spring-boot#51]
Hi !
I have created application and initialized EmbeddedHttpSession infinispan correctly (I suppose, because Spring Boot is running). Here is cache Configuration class:
```
@EnableCaching
@Configuration
@EnableInfinispanEmbeddedHttpSession(cacheName = "mysessions")
public class CacheConfigurationDefault {

    private final Logger log = LoggerFactory.getLogger(this.getClass());

    @Bean
    public SpringEmbeddedCacheManagerFactoryBean springCache() {
        log.warn("Embedded infinispan session cache activated...");
        return new SpringEmbeddedCacheManagerFactoryBean();
    }
}
```
To debug cache I have registered REST controller URL and injected cacheManager there
```
    @GetMapping(value = "/cache", produces = MediaType.TEXT_PLAIN_VALUE)
    public String getCache() {
        Cache<String, MapSession> cache = cacheManager.getCache("mysessions");
        return cache.getStatus().name();
    }
```
I use HttpSession instance with getAttribute() and setAttribute() to get/put objects into cache. As I understood Spring  should transparently put them into infinispan. However If I look into "cache" variable using breakpoint at REST controller there is no "session" or "mysessions" caches defined unless I call cacheManager.getCache("mysessions") for the fist time.  Session data is persistent between HTTP requests but I have no idea where is it stored. I think not at Infinispan. How should I correctly store/retrieve HttpSession objects to/from Infinispan?
Thanks

**Comment by vadimkim** [comment]
I think there is an issue at both `@EnableInfinispanEmbedded(Remote)HttpSession` implementations. Particularly according to spring-session documentation [httpsession-how](https://docs.spring.io/spring-session/docs/current/reference/html5/#httpsession-how) implementation should register Filter and extend HttpServletRequestWrapper to implement custom HttpSession. Otherwise HttpSession will not see cache provider and obviously that is why I don't see any HttpSessions at Infinispan

**Comment by slaskawi** [comment]
The implementation of Spring Session is based on Infinispan's `SpringCache` [1]. This object is being created by `SpringEmbeddedCacheManager` or `SpringRemoteCacheManager`, and acts as an implementation for `org.springframework.cache.CacheManager`. So in essence, you should be using the same `SpringCache`s, created by the same `CacheManager` for both, caching support and Spring Session support. Therefore, you should be able to grab session instances directly from the cache.

So my gut feeling is that somehow you have either two `CacheManager`s in your application or for some reason Spring Session and your code obtains different caches. 

There's an easy way to check this - just plug your Debugger into your application and please check if you're pointing into the same `EmbeddedCacheManager` instance from here [2] and from your code.

[1] https://github.com/infinispan/infinispan/blob/master/spring/spring4/spring4-common/src/main/java/org/infinispan/spring/session/AbstractInfinispanSessionRepository.java#L36
[2] https://github.com/infinispan/infinispan/blob/master/spring/spring4/spring4-embedded/src/main/java/org/infinispan/spring/session/configuration/InfinispanEmbeddedHttpSessionConfiguration.java#L27

**Comment by vadimkim** [comment]
Thank you for the hints, @slaskawi !
There were really 2 different objects, because I have created EmbeddedCacheManager using Spring constructor injection like this:
```
  private EmbeddedCacheManager cacheManager;

    @Autowired
    public UserSessionController(UserSessionData sessionData, HttpSession httpSession, EmbeddedCacheManager cacheManager) {
        this.sessionData = sessionData;
        this.httpSession = httpSession;
        this.cacheManager = cacheManager;
    }
```
It crates new instance that is not connected to Spring Sessions
Correct way (I hope) of doing this is like that:
    private CacheConfigurationDefault cacheConfigurationDefault;

```
    @Autowired
    public UserSessionController(CacheConfigurationDefault cacheConfigurationDefault, UserSessionData sessionData, HttpSession httpSession) {
        this.sessionData = sessionData;
        this.httpSession = httpSession;
        this.cacheConfigurationDefault = cacheConfigurationDefault;

    }
...
    @GetMapping(value = "/cache", produces = MediaType.TEXT_PLAIN_VALUE)
    public String getCache() throws Exception {
        SpringEmbeddedCacheManager cacheManager = cacheConfigurationDefault.springCache().getObject();
        Cache cache = cacheManager.getCache("mysessions");
        return cache.getName();
    }
```
I think you can close the issue because I will be able to find cache data now
