### ISSUE TITLE
Infinispan : Best way to implement cache in auto scaling mode in aws.

### ISSUE THREAD

**Issue by omverma22** [infinispan/infinispan-spring-boot#54]
Dear All,
                    We have deployed our servers into aws environment and running 2 instances of each server module. For example we have 2 spring boot jars running in 2 different instance. Load balancer are in placed to route the requests. We need to implement the cache which will keep the data updated in every instances. So when any data get updated it should update all other instances too. Please suggest us to figure out the best way to achieve it like embedded, remote, distributed etc.

Thanks,
Op

**Comment by galderz** [comment]
Not an issue. This is a question that should be directed to [Infinispan user forums](https://developer.jboss.org/en/infinispan/content?filterID=contentstatus%5Bpublished%5D~objecttype~objecttype%5Bthread%5D). Even then, this is very vague request ;)
