### ISSUE TITLE
Document accessing Infinispan cache metrics via Spring Actuator

### ISSUE THREAD

**Issue by kgilmer** [infinispan/infinispan-spring-boot#63]
I am able to access cache metrics with the Caffeine cache backend but when I swap in Infinispan I get no cache metrics.  In searches I was unable to find any definitive information on how to make this work with Spring Boot 2.0 and Infinispan.  I am able to access the metrics directly via a bean that retrieves the stats from org.springframework.cache.CacheManager but would prefer to consume the metrics from Actuator.

**Comment by kgilmer** [comment]
Hi @galderz , well for me I was simply trying to view cache statistics via Spring Actuator.  When configuring my application w/ Caffeine, I was able to get these metrics out of the box.  When switching backends to Infinispan, I was not able to find any metrics.  I'm guessing it's a configuration issue but was unable to find any documentation that lead me to a solution.

**Comment by karesti** [comment]
@kgilmer hi, are you using this starter?

**Comment by kgilmer** [comment]
hi @karesti I am using this Infinispan dependency w/ Spring Boot 2.0.6:

```
compile group: 'org.infinispan', name: 'infinispan-spring-boot-starter-embedded', version: '2.0.0.Final'
```

**Comment by karesti** [comment]
@kgilmer Maybe something is missing from our side! I've created a ticket to handle this 
https://issues.jboss.org/browse/ISPN-9668

**Comment by karesti** [comment]
@kgilmer the pr will be integrated soon and I will release 2.1 version of the starter

**Comment by karesti** [comment]
integrated

**Comment by kgilmer** [comment]
Thanks for the notice Katia!
