### ISSUE TITLE
InfinispanCacheMeterBinderProvider is always created and causes CastException if infinispan is not enabled

### ISSUE THREAD

**Issue by renierr** [infinispan/infinispan-spring-boot#67]
The InfinispanCacheMeterBinderProvider Actuator cast to the native Cache always if bean exist.
This is the Case if you depend on the starter.

But if you change the cache type in Spring to 'simple' this binder will cause an Class Cast Exception.

Solution would be to check if infinispan Cache is enabled or if cache type is 'infinispan'

**Comment by karesti** [comment]
Thank you for the reporting! The InfinispanCacheMeterBinderProvider is supposed to be created only when actuator dependencies are in the classpath. But anyway, there is a problem concerning the cache type too. I will open a JIRA

**Comment by karesti** [comment]
https://issues.jboss.org/browse/ISPN-9735

**Comment by DanielFran** [comment]
@karesti I have this error using spring-boot 2.1.1 + infinispan 9.4.4.Final + infinispan-spring-boot 2.1.0.Final:

> java.lang.IllegalStateException: Failed to load ApplicationContext
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.metrics.cache.CacheMetricsRegistrarConfiguration': Invocation of init method failed; nested exception is java.lang.ClassCastException: org.infinispan.jcache.embedded.JCache cannot be cast to org.infinispan.Cache
> Caused by: java.lang.ClassCastException: org.infinispan.jcache.embedded.JCache cannot be cast to org.infinispan.Cache
> 

Is this the same issue related here?

**Comment by karesti** [comment]
Yes, I think so. I did not take into account when implementing that people might use JCache API.
I'm fixing this issue straight after integrating with spring 5! (I have a PR already prepared...)

**Comment by karesti** [comment]
Correction has been merged and released with 2.1.1.Final, let me know if it works

**Comment by DanielFran** [comment]
@karesti The release his still not available. Can you check if there was any issue?
Thanks

**Comment by karesti** [comment]
@DanielFran Oh! Are you sure? I see it in maven central 
https://search.maven.org/artifact/org.infinispan/infinispan-spring-boot-starter-embedded/2.1.1.Final/jar

**Comment by karesti** [comment]
https://search.maven.org/search?q=g:org.infinispan%20AND%20a:infinispan-spring-boot-starter&core=gav

**Comment by DanielFran** [comment]
I still have issues in travis: https://travis-ci.org/jhipster/jhipster/jobs/465999815#L3132

Maybe it is some cache, I will check. Thanks

**Comment by karesti** [comment]
@DanielFran need any help for the failure ?

**Comment by karesti** [comment]
@DanielFran I saw you merged already, let me know please for the class cast exception and any other issue related.

**Comment by karesti** [comment]
Any time. We are in zulip chat for a fast contact and chat if you need it.
