### ISSUE TITLE
@ComponentScan included inside auto configuration classes

### ISSUE THREAD

**Issue by renierr** [infinispan/infinispan-spring-boot#68]
an  @ComponentScan annotation is set on the auto config classes without any include.
this makes it impossible to exclude the @Component annotated classes - see ticket 67

**Comment by renierr** [comment]
The only way i found is to disable the auto config classes as well

infinispan:
  embedded:
    enabled: false
    cache:
      enabled: false

**Comment by karesti** [comment]
I will open a JIRA here too, thank you!

**Comment by karesti** [comment]
@renierr I'm working on the ticket #67 bug I will see this issue after

**Comment by karesti** [comment]
@renierr I integrated the #67 that was related. The flags you mentioned above is the way it is supposed to work. Let me know if you see any other issue. Closing this now
