### ISSUE TITLE
Compatibility issue between infinispan-spring4-embedded and spring-session

### ISSUE THREAD

**Issue by fragonib** [infinispan/infinispan-spring-boot#74]
Hello,

I'm getting an exception when I try to use a web session backed on a infinispan datagrid from a servlet controller. The exception shows itself as follows:

```
java.lang.NoSuchMethodError: org.springframework.session.MapSession.setCreationTime(J)V
	at org.infinispan.spring.session.AbstractInfinispanSessionRepository.createSession(AbstractInfinispanSessionRepository.java:61) ~[infinispan-spring4-embedded-9.4.0.Final.jar:9.4.0.Final]
	at org.infinispan.spring.session.AbstractInfinispanSessionRepository.createSession(AbstractInfinispanSessionRepository.java:30) ~[infinispan-spring4-embedded-9.4.0.Final.jar:9.4.0.Final]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:332) ~[spring-session-core-2.1.1.RELEASE.jar:2.1.1.RELEASE]
```

Here there is a simple project with a test that manifest this error:
https://github.com/fragonib/infinispan-spring-boot-starter-issue

Could  `infinispan-spring-boot-starter:2.1.0.Final` have a compatibility issue during the interation of its transitive dependencies `infinispan-spring4-embedded-9.4.0.Final.jar:9.4.0.Final`  and `spring-session:2.1`?

**Comment by karesti** [comment]
@fragonib Hi, yes, indeed, there is an incompatibility. infinispan-spring4-embedded-9.4.0.Final brings another spring session version. I have to fix this issue, and specially, we need to use infinispan 10 (coming next year) to avoid any incompatibility.
Thanks for opening the issue, I will handle it

**Comment by karesti** [comment]
https://issues.jboss.org/browse/ISPN-9625

**Comment by DanielFran** [comment]
@karesti  you mean related with https://issues.jboss.org/browse/ISPN-7035 ?

@fragonib The fix is on is way: https://github.com/infinispan/infinispan/pull/6496

Waiting for next version to integrate in jhipster project: https://github.com/jhipster/generator-jhipster/issues/8683

**Comment by karesti** [comment]
yes, that's right, thanks for the input @DanielFran

**Comment by karesti** [comment]
@DanielFran I realised now I copied the wrong link, the issue I was referring to was ISPN-9789

**Comment by karesti** [comment]
I released 2.1.1.Final, soon it will be in maven central. Let me know if it works!

**Comment by karesti** [comment]
I will let it open, this issue, til I get your feedback @fragonib and @DanielFran

**Comment by DanielFran** [comment]
@karesti I updated project but still waiting for new version to be available in Maven Center (https://travis-ci.org/jhipster/jhipster/jobs/465999815)

Will let you know.

**Comment by karesti** [comment]
Spring session with the last version is integrated now I’m closing this
