### ISSUE TITLE
Map Hot Rod client properties to @ConfigurationProperties

### ISSUE THREAD

**Issue by slaskawi** [infinispan/infinispan-spring-boot#8]
Currently we support Hot Rod properties file. As it was discussed here, it might be beneficial to migrate them to `@ConfigurationProperties`, which turns on IDE competition.

A link to previous discussion: https://github.com/infinispan/infinispan-simple-tutorials/pull/20#discussion_r91289629

**Comment by snicoll** [comment]
Also, migrating everything is probably a bad idea if you have a lot of properties. Perhaps we would expose the most commonly used options, letting the user to reference the file for advanced use cases? I don't know about it much so maybe that's a bad idea.

**Comment by slaskawi** [comment]
Yes, we have a lot of those properties and I'm also not sure whether this should or should not be implemented. Let's leave it for now and see if there is any interest in this feature from community point of view.
